### PR TITLE
fix: Don't retire zero-length connection IDs

### PR DESCRIPTION
**Pull request by larseggert**
This makes us pass the `rebind-addr` QNS test.

### CODE REVIEW

**Review by martinthomson — COMMENTED** [review]
wheee!

Test case?

**Comment by larseggert** [comment]
Working on test cases in #2170. Should I merge all the feature fixes there?

**Comment by martinthomson** [comment]
Moving the code seems fine to me.

**Comment by larseggert** [comment]
Now part of #2170.

**Pull request closed without merging**
