### PR TITLE
Move datagrams below regular streams

### PR DESCRIPTION
**Pull request by martinthomson**
This will starve datagrams, which comes with its own risks.

Eventually, we'll need a better strategy.

@jesup is this a better starting for #1440?

### CODE REVIEW

**Review by KershawChang — APPROVED** [review]

**Comment by jesup** [comment]
LGTM.   Both ways work.

**Comment by KershawChang** [comment]
Hi @martinthomson , I am a bit confused about this patch.
Should we land this one or #1440? @jesup thinks we should land this one, but this is still a draft.
What do you think?
Thanks.

**Comment by KershawChang** [comment]
@martinthomson , could you resolve the conflicts of this patch?
I'd like to land this one, since this also includes some clean up. Thanks.

**Comment by martinthomson** [comment]
The blocker here is tests.  Neither patch includes tests and I really don't like having functionality that isn't tested.

**Comment by KershawChang** [comment]
> The blocker here is tests. Neither patch includes tests and I really don't like having functionality that isn't tested.

Ah, I see. I'll write a test for this.

**Comment by martinthomson** [comment]
I think that we got the tests in #1440, so I'm closing this one.

**Pull request closed without merging**
