### PR TITLE
neqo v0.7.3

### PR DESCRIPTION
**Pull request by mb**

### CODE REVIEW

**Comment by mb** [comment]
The fails on windows are unrelated. They are certainly not introduced by this commit and the last commit has them passing. I expect them to pass if CI would be run again if the CI didn't change since it ran the last time 2h ago for the previous commit. I'll rely on the merge queue CI to determine whether that is the case.

**Comment by mb** [comment]
ok, CI doesn't run again when clicking "Merge when ready". Force pushing to trigger CI again.

**Comment by mxinden** [comment]
```
FAILED: obj/lib/smime/smime.cmspubkey.obj 
ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe" /nologo /showIncludes /FC @obj\lib\smime\smime.cmspubkey.obj.rsp /c ..\..\lib\smime\cmspubkey.c /Foobj\lib\smime\smime.cmspubkey.obj /Fdobj\lib\smime\smime.c.pdb 
D:\a\neqo\neqo\nss\lib\smime\cmspubkey.c(153): error C2057: expected constant expression
D:\a\neqo\neqo\nss\lib\smime\cmspubkey.c(153): error C2466: cannot allocate an array of constant size 0
D:\a\neqo\neqo\nss\lib\smime\cmspubkey.c(153): error C2133: 'suppPubInfo': unknown size
[318/888] LIB D:/a/neqo/neqo/dist/Release/lib\ssl.lib
[319/888] CC obj\lib\smime\smime.cmsrecinfo.obj
[320/888] CC obj\lib\smime\smime.cmsreclist.obj
[321/888] CC obj\lib\smime\smime.cmssigdata.obj
[322/888] CC obj\lib\sqlite\sqlite.sqlite3.obj
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

I haven't seen this failure before. Does it persist on retry?

**Comment by mb** [comment]
Yes. It's also present on other PRs: #1761

**Review by larseggert — APPROVED** [review]

**Pull request merged**
