### PR TITLE
fix: Check for error when looking up packet number space

### PR DESCRIPTION
**Pull request by larseggert**
The crash signatures don't really give much of an indication of where exactly the issue is. Am kinda guessing it's this `unwrap` of the packet number space which was based on unverified network input (via `PacketNumberSpace::from`).

Possible fix for #1363.

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
What do you think of adding a `debug!` in case `get_mut` returns `None`? Otherwise, a `Error::ProtocolViolation` is very difficult to trace back to its origin as a user.

Either way, looks good to me.

(On the matter of `unwrap` in general, since we have been turning on more and more static checks, we could take the next step and prohibit calls to `unwrap` across all non-test code via [Clippy's disallowed methods](https://rust-lang.github.io/rust-clippy/master/#/disallowed_method). In cases where we do need an `unwrap`, we can use `expect` with verbal proof why the case is impossible. Worked well in previous codebases I worked on.)

**Review by martinthomson — COMMENTED** [review]
Test?

**Comment by larseggert** [comment]
Will get to both of your suggestions next week.

@mxinden I like the idea of getting rid of `unwrap` in that way. It seems that `unwrap` is behind many of the crashes that get reported on the neqo code.

**Comment by larseggert** [comment]
> Test?

So I'm struggling to write a test for this, which makes me wonder if the error is actually somewhere else...

**Comment by larseggert** [comment]
@martinthomson still no luck at getting a test that hits this. But I think we should merge this if only in the interest of code hygiene.

**Pull request merged**
