### PR TITLE
feat(transport): add ecn metrics to Stats

### PR DESCRIPTION
**Pull request by mxinden**
Adding 4 ECN metrics to `neqo-transport` `Stats`:

``` rust
    /// Number of paths known to be ECN capable.
    pub ecn_paths_capable: usize,
    /// Number of paths known to be ECN incapable.
    pub ecn_paths_not_capable: usize,
    /// ECN counts for outgoing UDP datagrams, returned by remote through QUIC ACKs.
    pub ecn_tx: EcnCount,
    /// ECN counts for incoming UDP datagrams, read from IP TOS header.
    pub ecn_rx: EcnCount,
```

---

Fixes https://github.com/mozilla/neqo/issues/2068.

Corresponding Phabricator Differential: https://phabricator.services.mozilla.com/D220062

### CODE REVIEW

**Comment by mxinden** [comment]
This pull request is ready for a first review.

Below is a screenshot of a local Firefox `about:telemetry` page, showing the two new metrics:

- A Scalar `ecn_paths_capability` keyed by `capable` and `not-capable`.
- A Histogram `HTTP3_ECN_CE_ECT0_RATIO` keyed by `tx` and `rx`, multiplied by a factor of `10_000`.

Screenshot 2024-08-24 at 15-48-29 Telemetry Data

**Review by larseggert — COMMENTED** [review]
One thing we need to check is whether `EcnCount[NotEct]` is correctly set by the current code in all cases, because that is not included in a received ACK-ECN frame.

**Comment by mxinden** [comment]
> One thing we need to check is whether `EcnCount[NotEct]` is correctly set by the current code in all cases

`EcnCount[NotEct]` is **not** correctly set for outgoing packets where marks are received through a QUIC ACK-ECN frame.

Would it be valid to derive `NotEct` as `largest_acked - ECT0 - ECT1 - ECN_CE` @larseggert?

Note that I am not making use of `EcnCount[NotEct]` in Firefox. That said, I agree that we should not expose an invalid `NotEct` value, that is 0.

**Comment by larseggert** [comment]
I'm wondering if we can omit `EcnCount[NotEct]` when we report, or even completely. `enum_map` can't handle that though AFAICT.

**Comment by larseggert** [comment]
> In case this derivative is valid, I would prefer, for the sake of completeness, exposing all 4. In case it is not, I prefer going with the first alternative proposed above.

I'm not sure that it is. Can we actually count them?

**Comment by mxinden** [comment]
> > In case this derivative is valid, I would prefer, for the sake of completeness, exposing all 4. In case it is not, I prefer going with the first alternative proposed above.
> 
> I'm not sure that it is. Can we actually count them?

As in _count how many `NotEct` datagrams we send_? I am not sure combining two measurement sources, i.e. (1) marks **received** through QUIC ACK-ECN and (2) the datagrams **send** is a good idea.

Say that a middlebox converts every `Ect0` to `NotEct`. Within the ECN validation timeframe, the local node would only send `Ect0` datagrams, while the remote node would only receive `NotEct`. The local node would then report an ECN count of 0 `Ect0` (derived from QUIC ACK-ECN) and 0 `NotEct` (derived from counting sent datagrams).

**Comment by larseggert** [comment]
Ah, sorry. This is all about reporting received marks. For received marks, the `NotEct` counts should always be correct, no?

**Comment by mxinden** [comment]
This pull request handles both:

1. ECN counts for outgoing UDP datagrams, returned by remote through QUIC ACKs.
2. ECN counts for incoming UDP datagrams, read from IP TOS header.

Our current discussion is about (1), i.e. the `EcnCounts` derived from QUIC ACK-ECN. Given that a QUIC ACK-ECN does not carry `NotEct`, the current `EcnCount` for (1) as implemented here is not correct, that is, it will always report 0 for `NotEct`.

**Comment by larseggert** [comment]
I think we should make it clear that the count is unknown then. Maybe with an `Option` or is this too unwieldy?

**Comment by mxinden** [comment]
I see 3 ways forward here:

1. Derive `EcnCount[NotEct]` based on the largest acknowledged packets.
2. Encode the fact that `EcnCount[NotEct]` is `0` at the type system level, e.g. via a custom `EcnCount` struct, or an `Option`.
3. Document the fact that `EcnCount[NotEct]` is `0` for outgoing UDP datagrams.

As discussed above (1) might not always be accurate. After some experimentation in my eyes (2) isn't worth the additional complexity. With https://github.com/mozilla/neqo/pull/2072/commits/512debae64018cd5ee29853315fe8c240aeabe64 I opted for (3), especially since `EcnCount[NotEct]` is never used at the consumer side, i.e. Firefox.

@larseggert is (3), i.e. https://github.com/mozilla/neqo/pull/2072/commits/512debae64018cd5ee29853315fe8c240aeabe64, a valid option for you?

**Comment by larseggert** [comment]
I think 3 is fine for this PR. We can revisit if we need to.

**Review by larseggert — APPROVED** [review]

**Comment by larseggert** [comment]
@mxinden fix the conflict, please?

**Comment by mxinden** [comment]
Will fix the Rust doc failures in a bit.

**Pull request merged**
