### PR TITLE
ci: Try longer when downloading NSS and NSPR

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Review by mxinden — APPROVED** [review]

**Comment by larseggert** [comment]
I actually wonder if we should try `hg` once and if that doesn't work, fall back to the `git` mirror instead?

**Comment by larseggert** [comment]
The `git` mirror _should_ be up-to-date, but apparently there are sometimes sync issues.

**Comment by martinthomson** [comment]
A failure in git synchronization could be treated like any other CI failure.  It makes us canaries for that process, but I think that is a reasonable thing for us to do.

**Comment by larseggert** [comment]
OK, closing this in favor of #1710.

**Pull request closed without merging**
