### PR TITLE
fix: Resurrect #1662

### PR DESCRIPTION
**Pull request by larseggert**
Botched the "merge from main" on #1662. Reverted the merge. This PR has the changes in #1662, rebased to main. Sorry for the mess.

### CODE REVIEW

**Comment by larseggert** [comment]
@martinthomson at least you should have better flamegrahs now. Still looks slower.

**Comment by larseggert** [comment]
@martinthomson should we refactor this and pull the cleanups into the main branch?

**Comment by larseggert** [comment]
@martinthomson I rebased it onto the current `main`. Should hopefully make it easier to revert the change to `VecDeque`?

**Comment by martinthomson** [comment]
Thanks.  I started to poke at this yesterday and ran into a crash bug in the NSS initialization tests.  I'm out of time though.  This will have to wait a week or two.  I'll look after the rebasing for that.

**Comment by larseggert** [comment]
@martinthomson any chance we could land the cleanups soon-ish?

**Comment by martinthomson** [comment]
I've a new branch with fixes on it.  Some seem to improve things, but we can check there.

**Pull request closed without merging**
