### PR TITLE
ci(qns): run all tests and remove msquic & quic-go

### PR DESCRIPTION
**Pull request by mxinden**
Run all QUIC Interop Runner testcases.

For the sake of reducing runtime, this commit also removes msquic and quic-go, leaving only ngtcp2 and neqo itself. Reason being, that ngtcp2 is the only implementation that passes all testcases, especially the ECN testcase.

Long term we can consider parallelizing the test execution as suggested by Marten in https://github.com/quic-go/quic-go/pull/4339#issuecomment-1977606709.

### CODE REVIEW

**Comment by larseggert** [comment]
Would we not also want to remove `neqo` and only run `neqo-latest`?

**Comment by mxinden** [comment]
I had in mind to catch regressions between neqo versions, i.e. between `neqo-latest` and `neqo` (last `main` commit). I don't feel strongly about it.

**Comment by larseggert** [comment]
Yes, tests should be sufficient.

**Comment by larseggert** [comment]
> I had in mind to catch regressions between neqo versions, i.e. between `neqo-latest` and `neqo` (last `main` commit). I don't feel strongly about it.

Yeah, that makes sense. Leave it in. Esp. if we do `-t onlyTests`.

**Comment by mxinden** [comment]
Replaced by https://github.com/mozilla/neqo/pull/1847/.

**Pull request closed without merging**
