### PR TITLE
change u64 to streamId

### PR DESCRIPTION
**Pull request by michiboo**
Hi I changed the type for stream_id from u64 to StreamId, as describe in #346

Where can I add the type to public interface?

### CODE REVIEW

**Comment by martinthomson** [comment]
in lib.rs add `pub use stream_id::StreamId`. But first, you need to get this passing tests. `cargo fmt` is the first step.

**Comment by michiboo** [comment]
Hi for qdebug, I try to use stream_id.0 but it has private restriction, how should I go around this?

**Comment by martinthomson** [comment]
`#[derive(Debug)]` if you can use `{:?}`, or you can implement `Display`.

Or you can use the `Into` implementation.  Or you can make the `u64` "pub".

**Comment by agrover** [comment]
poke, this looks like it needs some rebasing but has received a favorable overall response.

**Comment by agrover** [comment]
Thanks so much for updating!!!

So... I know this is contrary to what @martinthomson said above but I would really prefer that StreamId implement `Display` rather than making the u64 pub. This should be something like:
```
impl Display for StreamId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f,"{}", self.as_u64())
    }
}
```
but then all the `.0`s in all the qdebugprints go away.

Also, running `git grep "stream_id: u64"` shows a bunch of hits still. Those spots should all be changed over too. Let's go all the way.

**Comment by agrover** [comment]
Finally, let's re-export StreamId at the top level of neqo_transport so `use neqo_transport::stream_id::StreamId` becomes `use neqo_transport::StreamId`

**Comment by martinthomson** [comment]
What @agrover said would be great, I agree.

**Comment by agrover** [comment]
@michiboo ping?

**Pull request closed without merging**
