### PR TITLE
Path MTU fixes

### PR DESCRIPTION
**Pull request by martinthomson**
Change the default path MTU
Factor path code into its own file
Include Initial padding in accounting for the Inital packet bytes
Refactor tests

This will interact with the 2 packet PTO change in #448, but I can sort that out fairly easily.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
What was the reasoning for this? It appears to violate the RFC requiring MTU to be 1280 (and at least in naive initial connections there is lot of padding so it isn't strictly required - but maybe it is in some cases?).

**Comment by martinthomson** [comment]
The RFC requires that the MTU be at least 1280.  It doesn't say anything about what individual endpoints decide to additionally require.  In this case, as we are able to use TCP fallback, we have a little flexibility in terms of what MTU we insist upon.  Consistent padding will ensure that we don't get a connection unless the larger MTU is available.

**Comment by TheBlueMatt** [comment]
Sorry, I meant the QUIC RFC, not the IP RFC. Last I heard it MUSTs that PMTU be set to 1280 unless PMTUD is implemented. I suppose one could argue this "implements" PMTUD but that does seem to ignore the spirit of the RFC, certainly falling back to TCP in case the MTU is 1280 isn't ideal.

**Comment by martinthomson** [comment]
Concretely, the normative requirement is [at least 1200](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-initial-datagram-size).

The bit that might concern you here is [this paragraph](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-14.1-3), which says that you can exceed 1200 if you know that the path supports it.  As most paths on the Internet support larger MTUs, we're gambling on this being the case here too.  As every extra byte we manage to cram in without doing PMTUD is a huge performance gain, we're betting against the (low) probability that the path has a small MTU.

As this stack is primarily intended for use as a client, we're able to rely on Alt-Svc (where we retain a TCP connection until QUIC is proven viable) or happy eyeballs (where we attempt both TCP and QUIC in parallel).  If this were a server, we'd probably want to cap the maximum datagram size to the client datagram size.

**Comment by TheBlueMatt** [comment]
Ah, I'm out of date by 80 bytes :)

I suppose once [PMTUD is implemented](https://github.com/mozilla/neqo/issues/243) the initial frames will drop back down to 1200 and then send parallel PING/PADDING frames to at least get one DPLPMTUD RTT in before the response comes in (I admit I'm not 100% clear on when different bits of the protocol are allowed to be sent)?

**Pull request merged**
