### PR TITLE
Sanitize CONNECTION_CLOSE from application

### PR DESCRIPTION
**Pull request by martinthomson**
This recent requirement ensures that application-specific details don't leak.

I tested this by having the connection close.  I also tweaked the server so that goes from an initial state to closed without going to closing.  That avoids creating extra state on servers that receive bogus Initial packets.

### CODE REVIEW

**Comment by agrover** [comment]
maybe wait to rebase this again until after #583 goes in, since that will likely generate more conflicts.

**Comment by martinthomson** [comment]
More rebasing.

**Comment by agrover** [comment]
Changing `close()` to take an owned string seems unrelated to other, more worthwhile changes (and is also a source of conflicts). Maybe drop that, or at least give it its own commit?

**Comment by martinthomson** [comment]
Superseded by #625.

**Pull request closed without merging**
