### PR TITLE
Extract the expiration time from a resumption token

### LINKED ISSUE #929: Expiration time for a resumption token
Necko use the expiration time to decide if it should replace a token that is already in the cache.
The time is read from the resumption token. The token from neqo does no contain only a raw TLS token but it also has other parameters so to use nss function to extract the expiration time in necko would mean that we need to parse the token and find the start of the TLS token. I would like to avoid doing this. here is 2 option:
1) neqo does the parsing of the token and return the token with the expiration time
2) we assume that the new token is newer and we always replace a token in the cache

### PR DESCRIPTION
**Pull request by ddragana**
Fixes #929

### CODE REVIEW

**Comment by ddragana** [comment]
This was easier than I thought.

**Review by martinthomson — COMMENTED** [review]
I just found this review sitting here.  I think that this is generally good, but have some thoughts for improvement.

**Comment by ddragana** [comment]
Most of this comments are already addressed if you look at the last version:
https://github.com/mozilla/neqo/commit/94c70031d3fed736355701f74edd9f1ebe896ab9

**Review by martinthomson — APPROVED** [review]

**Comment by martinthomson** [comment]
Mergify is busted.  We need to decide whether to keep it or not, because I can't see how it should fail like this.

**Pull request merged**
