### PR TITLE
feat: Add the ability to send PING frames

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Review by martinthomson — COMMENTED** [review]
I mentioned an alternative approach to getting a frame through in Slack.  I'm not completely opposed to expanding the API surface, but it might be easier to use frame injection for the tests we care about.

**Comment by larseggert** [comment]
OK, if we end up needing PINGs to force idle I will look into using the backdoor instead of this.

**Comment by larseggert** [comment]
Making this a draft since we may not need/want this.

**Comment by larseggert** [comment]
Closing this. Can reopen if we intend to support this API.

**Pull request closed without merging**
