### PR TITLE
Use the mozbuild crate when building in gecko

### PR DESCRIPTION
**Pull request by glandium**
See [bug 1751331](https://bugzilla.mozilla.org/show_bug.cgi?id=1751331).

### CODE REVIEW

**Comment by glandium** [comment]
The clippy error comes from the fact the branch is derived from v0.5.6 rather than main, because I wanted it to be merged rather than rebased, so that we could update mozilla-central without pulling the changes since v0.5.6.

**Review by martinthomson — APPROVED** [review]
Thanks for this @glandium, this is a very nice change.  I can confirm the clippy error is not your fault (it's mine).

**Comment by martinthomson** [comment]
Going YOLO on the merge to main.  @glandium, do you want to land a version with 0.5.6 plus your changes in m-c?  (Maybe @ddragana can help with the details as I just timed out for the week.)

**Comment by glandium** [comment]
I was hoping you'd do an actual merge, such that I could just use the revision from this PR, but it's too late for that now...

**Comment by glandium** [comment]
One possibility would be create a branch for f1cd349.

**Comment by martinthomson** [comment]
@ddragana is in the best position to work that out.  If we're landing an 0.5.7 with new features soon, that might be easier.

**Comment by ddragana** [comment]
Sorry for the delay. I will create 0.5.7 and landed it into m.-c. today.

**Pull request merged**
