### PR TITLE
Uppercase in header field

### PR DESCRIPTION
**Pull request by i-am-jeetu**
Draft for #753.

### CODE REVIEW

**Comment by ddragana** [comment]
Looks good.

**Comment by martinthomson** [comment]
Yep, but it needs some tests to demonstrate that it works and to ensure that we don't accidentally break it.

**Comment by i-am-jeetu** [comment]
>produce a stream error H3_GENERAL_PROTOCOL_ERROR if header block is malformed 
> - the presence of prohibited fields or pseudo-header fields

Where can I find the list of prohibited header field names? It isn't this one right? [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)

**Comment by ddragana** [comment]
> > produce a stream error H3_GENERAL_PROTOCOL_ERROR if header block is malformed
> > 
> > * the presence of prohibited fields or pseudo-header fields
> 
> Where can I find the list of prohibited header field names? It isn't this one right? [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)

this is about pseudo-headers fields. They are define in section "4.1.1.1.  Pseudo-Header Fields" in https://tools.ietf.org/html/draft-ietf-quic-http-29

**Comment by agrover** [comment]
Apparently all PRs against master branch were automatically closed when we made 'main' the default branch and deleted 'master'. :frowning_face: I'm really sorry, I did not anticipate this. If you would be so kind, please open a new PR against 'main' that references this one so we can continue to move forward. Sorry again, and thanks.

**Pull request closed without merging**
