### PR TITLE
Add ccov workflow

### PR DESCRIPTION
**Pull request by valenting**

### CODE REVIEW

**Comment by KershawChang** [comment]
I notice this error.
```
[2023-11-28T15:03:18.865Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Is this normal?

**Comment by larseggert** [comment]
A `CODECOV_TOKEN` needs to be added to the repo: https://docs.codecov.com/docs/codecov-uploader#upload-token

(Also, you need to actually generate coverage information. I am working on a PR that will do this and also test on MacOS and Windows: https://github.com/larseggert/neqo/blob/feat-expand-ci-matrix/.github/workflows/check.yml)

**Comment by valenting** [comment]
I tried to follow the instructions here: https://app.codecov.io/gh/mozilla/neqo/new

Step 1: add repository token as [repository secret](https://github.com/mozilla/neqo/settings/secrets/actions)
Admin required to access repo settings > secrets and variable > actions

@larseggert you have more experience with this. Could you have a look if this is set up properly?

**Comment by larseggert** [comment]
Maybe restart the action? If it ran before you added the token, that would explain the failure. (I don't think I have permissions to diddle the necessary knobs myself.)

**Comment by larseggert** [comment]
Scratch the last bit, I do!

**Comment by larseggert** [comment]
I opened #1500, which generates the coverage information, and also uploads it.

**Comment by larseggert** [comment]
I think this is redundant with #1500.

**Pull request closed without merging**
