### PR TITLE
Fix option conflict and change default values

### LINKED ISSUE #638: -d option to neqo-http3-server is conflicted
In #611, we added a -d option, but that is used by the server code already to identify where the NSS database is.  We should pick a different option.  Do we need a short code for this option?

### PR DESCRIPTION
**Pull request by ddragana**
Fixes #638

### CODE REVIEW

**Comment by agrover** [comment]
alternate proposal: don't give these options short options.

**Comment by agrover** [comment]
For the same values? They can go too.

**Comment by martinthomson** [comment]
I don't care so much about the defaults, but it's probably good to have consistent defaults.

I do care that the arguments use the same short forms.

**Comment by martinthomson** [comment]
FWIW, I'm with Andy on dropping the short tags, but this is fine.

**Pull request merged**
