### PR TITLE
chore: Removed InternalErrors added in #1085 

### PR DESCRIPTION
**Pull request by Grubba27**
I've just removed all of the internal errors as issue  #1086 don't know if we need to remove other code, the issue description was not clear to me. 
If is needed to make any changes I gladly would do it

### CODE REVIEW

**Comment by martinthomson** [comment]
I guess my question is for @ddragana: what does the telemetry for these look like?

If we're OK with removing all of them, we should remove the enum variant from `Error` and the CI checks as well.

**Comment by ddragana** [comment]
> I guess my question is for @ddragana: what does the telemetry for these look like?
> 

Looking at the recent data: 
InternalError(5) occurred 2 times in a week and InternalError(4) occurred once. 
This is very low. I would prefer that these numbers are 0 but we will not be able to investigate this.  
We can remove it.

> If we're OK with removing all of them, we should remove the enum variant from `Error` and the CI checks as well.

**Comment by larseggert** [comment]
@martinthomson @KershawChang is this still something we want to do? Or is this OBE?

**Comment by martinthomson** [comment]
We're not really using them, so it would be cleaner not to have them.

**Comment by larseggert** [comment]
@Grubba27 want to take a stab at resolving the conflicts that have accumulated?

**Comment by larseggert** [comment]
I fixed the conflicts. I'll note that there are still occurrences of `InternalError` in the code in this PR. Not sure if that is to be expected.

**Comment by martinthomson** [comment]
Well, we could just purge the lot.  I think that the telemetry has served its purpose, so that might be OK.

This patch doesn't build because it means that a few functions go from returning both Ok or Error in different circumstances to always returning `Ok(())`, which clippy rightfully complains about.  There also appears to be some other problems.

**Comment by martinthomson** [comment]
It probably requires a little bit of analysis, but these are all places where we would have previously had an assertion (`assert!()` or maybe `debug_assert!()`.  I would be OK collapsing this all onto a single item and removing the number, which is an awkward thing to maintain.

**Review by larseggert — APPROVED** [review]

**Pull request merged**
