### PR TITLE
Switch from chrono to time 0.3

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]

**Comment by martinthomson** [comment]
We can't merge this until we sort out the MSRV situation.  See #1421.

**Comment by glandium** [comment]
Rebasing on top of #1423 shows that clippy is not happy with the undocumented panic that the unwrap adds.

**Comment by martinthomson** [comment]
Easier to generate the comment than deal with the warning; I'll send you a PR.

**Comment by glandium** [comment]
I rewrote the patch to not use unwrap, actually.

**Review by martinthomson — APPROVED** [review]
Perfect!

**Pull request merged**
