### PR TITLE
test: Let packets be modified with a closure during tests

### PR DESCRIPTION
**Pull request by larseggert**
Broken out of #1678 to reduce the size of that PR.

### CODE REVIEW

**Comment by larseggert** [comment]
is there a way to _drop_ a packet inside the closure, and not just modify it?

**Comment by mxinden** [comment]
> is there a way to _drop_ a packet inside the closure, and not just modify it?

Wouldn't the below work?

``` diff
- mut modifier: impl FnMut(&mut Datagram),
+ mut modifier: impl FnMut(Datagram) -> Option<Datagram>,

**Comment by larseggert** [comment]
Ah yes! I think that is what @martinthomson also suggested, but my brain is fried after the IETF.

**Review by martinthomson — APPROVED** [review]

**Comment by martinthomson** [comment]
Merge override due to known failed test.  Separately, the qns build was taking a worrying amount of time.  I cancelled at 22 minutes.  We might want to look into that.

**Pull request merged**
