### PR TITLE
transport: Remove derive_more dependency.

### PR DESCRIPTION
**Pull request by emilio**
I need to update this dependency to get rid of old syn and quote in
mozilla-central.

But it seems like in this case it's easier to get rid of it, it saves like five
lines of code, and brings in a ton of dependencies.

Let me know if you want to keep it and update the dependency instead, but I
think it's not worth it in this case.

### CODE REVIEW

**Comment by emilio** [comment]
r? @ddragana 

(Also, information on how to get this patch into Gecko would be appreciated. Thanks!)

**Comment by emilio** [comment]
Ah, guess it's just a matter of updating the git revision in `netwerk/socket/neqo_glue/Cargo.toml`, that wfm :)

**Comment by ddragana** [comment]
> Ah, guess it's just a matter of updating the git revision in `netwerk/socket/neqo_glue/Cargo.toml`, that wfm :)

in bug 1596069, I have switch to use `tag`, so we will need to make a new release. When do you want this to be in m.-c.?

**Comment by emilio** [comment]
No particular rush, whenever you get to it :)

**Pull request merged**
